apiVersion: habitat.sh/v1beta1
kind: Habitat
customVersion: v1beta2
metadata:
  ## Name of the Kubernetes resource.
  name: hab-webserver
spec:
  v1beta2:
    ## Name of the Habitat service package exported as a Docker image.
    image: chefshafique/hab-webserver:0.1.0-20181113211035
    ## Number of desired instances.
    count: 3
    ## An object containing parameters that affects how the Habitat service
    ## is executed.
    service:
    ## Name of the Habitat service.
      name: hab-webserver
    ## Habitat topology of the service.
      topology: standalone
---
apiVersion: v1
kind: Service
metadata:
  name: hab-webserver
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    habitat-name: hab-webserver

